project_id = "oqobnhwwwygslcpmpurq"

[functions.extract-invoice-data]
verify_jwt = true

[functions.extract-ana-document]
verify_jwt = true

[functions.clasificar-hts-ai]
verify_jwt = true

[functions.motor-aprendizaje-hts]
verify_jwt = true

[functions.orion-listener]
verify_jwt = false
